config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :employees
  devise_for :users
  root to: "home#index"
  # resources :attendences
  # get '/record_attendence' => "home#login_time", as: :attendences
  get "/record_attendence" => "home#login_time", as: :log_time
  get "/analytics" => "analytics#index", as: :analytics

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
	belongs_to :employee
	validates :in_time, uniqueness: {scope: :employee_id} 
  scope :today, -> { where('in_time::DATE =?', Time.current) }
  scope :this_month, -> { where(in_time: (Time.current.beginning_of_month..Time.current.end_of_month)) }
  scope :late, -> { where(status: "Late") }
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :attendences

	validates_presence_of :username
	validates_uniqueness_of :username
	validate :check_empty_space

	def check_empty_space
	  if self.username.match(/\s+/)
	    errors.add(:username, "No empty spaces please :(")
	  end
	end	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
  	admin == true
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
  	if params[:u_name].present?
  		@employee = Employee.where(username: params[:u_name]).first
  		@a = @employee.attendences
  	else
  		@a = Attendence.today
  	end
		t = @a.collect{ |w| w.in_time.to_i }
    if t.present? && @a.present?
		  @average_time = (t.sum/t.count)
		  @average =  Time.zone.parse(DateTime.strptime(@average_time.to_s,'%s').to_s)
    else
      @average = 0
      @average_time = 0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to root_url, notice: 'User has been successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:username)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @employees = Attendence.order(in_time: :desc)
     @attendences = @employees.to_a.group_by { |w| w.in_time.to_date }       
  end 

  # this method will do the logic
  def login_time
  	emp = Employee.where('lower(username) =?', params[:username].downcase).first
 	  # get the emp username if exists 
  	if emp.present?
  		Attendence.create(employee_id: emp.id, in_time: Time.now.in_time_zone)
      redirect_to root_url, notice: "Thank You #{emp.username} !, your arrival has been successfully tracked."
  		# attendence will be logged for the day.
  	else
  		redirect_to root_url, alert: 'sorry we could not find you, try again or make a new user if u are a new user'
  		# notifies if does not exists
  	end
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

  def get_attendences(name = nil)
    if name.present?
      name.attendences
    else  
      Attendence.all
    end
  end

  def attendence_status(a)
    in_time = a.in_time.strftime("%H:%M:%P")
    login_time_decided_by_office = Time.parse('10:00 am').strftime("%H:%M:%P")
    if in_time > login_time_decided_by_office
      a.update_attributes(status: 'Late')
      "<span class='btn btn-xs btn-danger'> #{a.status} </span>".html_safe
    else
      a.update_attributes(status: 'On Time')
      "<span class='btn btn-xs btn-success'> #{a.status} </span>".html_safe
    end
  end

  def average_late(date)
    
  end

  def averate_on_time(date)
    
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/analytics/index.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<div class="row">
	<div class="col-lg-6 col-sm-6 col-xs-12">
		<div class="well">
		<% user = @employee.present? ? @employee.try(:username) : "All Employees" %>
			<h4>Average Login Time of <%= user %> </h4>
			<%= @average > 0 ? @average.strftime('%H:%M %P') : 0.0 %>
		</div>
	</div>

	<div class="col-lg-6 col-sm-6 col-xs-12">
		<div class="well">
			<h4>Late Count This Month </h4>
			<% if @employee.present? %>
				<%= @employee.attendences.late.count %>
			<% else %>
			<% end %>
		</div>
	</div>


	<div class="col-lg-6 col-sm-6 col-xs-12">
		<div class="well">
			<h4>Average Timings Percent </h4>
			<% if @average > 0 %>
				<% hnm = @average.strftime('%H:%M').split(":") %>
				<%= hour, minute = hnm[0], hnm[1] %>
			<% end %>
			<hr>
		</div>
	</div>


<!-- 	<div class="col-lg-6 col-sm-6 col-xs-12">
		<div class="well">
			<h4>Timing Graph </h4>
			<%#= line_chart @a.this_month.group(:status).group_by_day(:in_time).count %><hr>
		</div>
	</div> -->

<!-- 	<div class="col-lg-6 col-sm-6 col-xs-12">
		<div class="well">
			<h4>Average Timings Percent </h4>
    		<%#= line_chart Attendence.where(status: "late").pluck("in_time").map { |c| { name: c, data: Attendence.today.count }  }, discrete: true %>
			<hr>
		</div>
	</div>
</div>
 -->
<style type="text/css">
	.well {
		border :none;
	}
</style>

app/views/employees/_form.html.erb
<%= form_for(employee, html: {class: "form-inline"}) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Make User", class: "btn btn-md btn-success" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.username %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1><hr>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @employee.username %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/index.html.erb
<%= form_tag log_time_path, method: :get, class: "form-inline" do %>
	<%= text_field_tag :username, '', class: "form-control", placeholder: "enter user name" %>
	<%= submit_tag 'Track', class: "btn btn-md btn-success" %>
<% end %>
<hr>

<h3>Daily Attendnece</h3>
<% @attendences.each do |date, attendences| %>
	<table class="table">
		<tr><td class="text-danger"><h4><%= time_tag date %></h4></td></tr>
		<tr>
			<th>User Name</th>
			<th>In Time</th>
			<th>Status</th>
		</tr>
		<% attendences.each do |a| %>
		<tr>
			<td><%= link_to a.employee.username, analytics_path(u_name: a.employee.username) %></td>
			<td><%= a.in_time.strftime('%H : %M %P') %></td>
			<td><%= attendence_status(a) %></td>
		</tr>
		<% end %>
	</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ETracking" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <link href='https://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body style="font-family: 'Exo 2', sans-serif;">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ETracking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Create New User", new_employee_path %></li>
            <li><%= link_to "Analytics", analytics_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to current_user.email,'#' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% if current_user.admin? %>
              <li><%= link_to 'View All Employees', employees_path %></li>
            <% end %>
            <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

<!--       <footer>
        <p>&copy; Company 2016</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>